name: 'List Changed Files'
description: 'Lists files that differ between the current branch and a specified base branch'
inputs:
  base-branch:
    description: 'The branch to compare against (e.g., main)'
    required: true
    default: 'main'
outputs:
  changed-files:
    description: 'A newline-separated list of changed files'
    value: ${{ steps.diff.outputs.changed-files }}
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Fetch full history for accurate diff

    - name: Fetch base branch and list changed files
      id: diff
      shell: bash
      run: ${{ github.action_path }}/script.sh ${{ inputs.base-branch }}
      env:
        GITHUB_SHA: ${{ github.sha }}
        GITHUB_REF_NAME: ${{ github.ref_name }}

    - name: Print changed files
      shell: bash
      run: |
        echo "Changed files:"
        echo "${{ steps.diff.outputs.changed-files }}"

