name: Use Diff Files Action

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  list-changed-files:
    runs-on: ubuntu-latest
    steps:
      - name: List changed files
        uses: ./.github/actions/diff-files
        id: diff
        with:
          base-branch: 'main'

      - name: Use changed files in another step
        run: |
          echo "Changed files output:"
          echo "${{ steps.diff.outputs.changed-files }}"
